<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>

    <!-- Please use caution adding a dependency to MSBuild packages. Use latest for testing and
         use the minimum version for compilation for back compat. -->
    <MicrosoftBuildPackageVersion>17.11.4</MicrosoftBuildPackageVersion>
    <MicrosoftBuildMinimumPackageVersion>16.11.0</MicrosoftBuildMinimumPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageVersion Include="Microsoft.Bcl.TimeProvider" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Build" Version="$(MicrosoftBuildPackageVersion)" />
    <PackageVersion Include="Microsoft.Build.Framework" Version="$(MicrosoftBuildPackageVersion)" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildPackageVersion)" />
    <PackageVersion Include="Mono.Cecil" Version="0.11.6" />
    <PackageVersion Include="NuGet.ProjectModel" Version="6.14.0" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="System.Text.Json" Version="8.0.6" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.0.15" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="PolySharp" Version="1.15.0" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator" Version="5.0.0-1.25277.114" />
  </ItemGroup>

</Project>
